# Generated by Django 3.2.2 on 2021-06-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_thumnbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumnbnail',
            new_name='thumbnail',
        ),
    ]
